### ISSUE TITLE
Error while running the jupyter notebook named "001_dude_horizontal.ipynb"

### ISSUE THREAD

**Issue by sawsimeon** [oddt/rfscorevs#1]
Hi, 

I got an error when running the notebook though I could load all of the required modules.  This is the error.

![image](https://user-images.githubusercontent.com/8380791/30434563-d1975b90-9991-11e7-8c94-8a090e380fa4.png)

Here is my sessioninfo.

![image](https://user-images.githubusercontent.com/8380791/30434667-09e7fcac-9992-11e7-918d-d1139a338c43.png)

**Comment by mwojcikowski** [comment]
I see you have a sklearn version 0.19. I'm guessing that there is an issue with the API of sklearn's cross validation, which has changed since the publication.

I can't really say for sure what is the exact problem, since there is no full trace stack. Could you send full trace stack or a full notebook?

**Comment by mwojcikowski** [comment]
Ok, I managed to reproduce the error - it's the pandas which complains about integer column names. Change at the beginning of the cell appropriate lines to:

```
    if v == 1:
        col_range = list(map(str, range(1,37)))
        np_type = np.uint16
    elif v == 2:
        col_range = list(map(str, range(1,217)))
        np_type = np.uint16
    elif v == 3:
        col_range = list(map(str, range(1,43)))
        np_type = np.float16
```

This should fix the problem for you. Let me know if it helped.

Note that you need at least 16GB+ of ram to successfully train the models.

**Comment by sawsimeon** [comment]
Hi, Thanks alot, It does not throw errors, and it does run like charm and use all of the CPU. And again, thanks a lot. This is not related to this issue but I would like to say it. I could not find the file named "dude_per_target_final.csv" . Is this csv file is generated after we train the model?
![image](https://user-images.githubusercontent.com/8380791/30438157-ba5aad52-999a-11e7-89e4-830458792546.png)

**Comment by mwojcikowski** [comment]
The `dude_per_target.csv` is generated by `001_dude_per_target.ipynb` and require a lot of computing. The `_final` suffix is my mistake and I must fix it, but it's the same file.

**Comment by sawsimeon** [comment]
Thanks alot. Since the issue index error from pandas is solved by making column names as a list, I will close the issue now. And by that way, the the rf-score-vs works perfectly for window binary. Great job. And Thanks again. 

![image](https://user-images.githubusercontent.com/8380791/30466539-bc197402-9a08-11e7-857a-9b7fdfb24558.png)
