### ISSUE TITLE
How to train  new data?

### ISSUE THREAD

**Issue by pincher-chen** [oddt/rfscorevs#2]
I  found the rf-score-vs is a scoring function, and can not train again.
```
./rf-score-vs 
usage: rf-score-vs [-h] [-n N_CPU] [--version] [-i {sdf,mol2,pdb,pdbqt}]
                   [-o {csv,sdf,mol2,pdb,pdbqt}] [-O OUT_FILE]
                   [--receptor RECEPTOR] [--field SAVE_FIELDS]
                   in_file [in_file ...]
rf-score-vs: error: too few arguments
```
I want to train dud-e database, but i found  the features in head1_full can not be used by 
 the rf-train in https://github.com/HongjianLi/RF-Score. The dud-e datasets are different from pdbbind datasets, for the former has active/decoy while the latter has experiment data. How did you train the dud-e data? or how did you get rf-score-vs in details? Could you give me some guides?

**Comment by mwojcikowski** [comment]
The final scoring function models are trained in a [notebook](https://github.com/oddt/rfscorevs/blob/master/001_final_SF.ipynb) enclosed in this repo. It produces `.pickle` files which are scikit-learn `RandomForestRegressor` models compiled with [sklearn-compiledtrees](https://github.com/ajtulloch/sklearn-compiledtrees). 


The `rf-score-vs` binary itself is created with code in separate repo: [oddt/rfscorevs_binary](https://github.com/oddt/rfscorevs_binary) with pyinstaller to create single file executable. All code is executed on CI (Travis and Appveyor).

The rf-train from Hongjian Li was not used by us to create the RF-Score-VS. Although I thought it **may** be possible to use our CSVs to train models using their software after renaming and reordering columns in our CSVs to match theirs, but it seams that a lot of variables is hard-coded in [rf-train](https://github.com/HongjianLi/RF-Score/blob/master/src/rf-train.cpp#L19-L41) (such as the number of training samples - 1105). So the final answer is that without substantial changes to `rf-train` it's not possible to train RF-Score-VS models.

Hope that helps.
