### ISSUE TITLE
000_MASTER_plots.ipynb not working by missing dude_classical_final.csv and dude_classical_final_nfolds.csv

### ISSUE THREAD

**Issue by rydia001** [oddt/rfscorevs#4]
Hello, I am highly interested in your work and I want to compare my method with your method.

As mentioned in the title, 000_MASTER_plots.ipynb showed errors due to missing dude_classical_final.csv and dude_classical_final_nfolds.csv .
I failed to fix them since the docking score information is not included in the dataset.
So, could you provide dude_classical_final.csv and dude_classical_final_nfolds.csv?

**Comment by mwojcikowski** [comment]
Good catch, these files are indeed missing I will upload them to fix that issue.
