### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load libmkl_def.so. [17]

### ISSUE THREAD

**Issue by drc007** [oddt/rfscorevs#5]
Hi,

Trying to run on Google CoLab and I get this error

Intel MKL FATAL ERROR: Cannot load libmkl_def.so.

Jupyter notebook is here

https://www.macinchem.org/reviews/JupyterDocking/jupyterdocking.php

**Comment by drc007** [comment]
Reinstalled Linux on Jupyter CoLab and error seems to be resolved?

**Comment by mwojcikowski** [comment]
It seems like your environment was missing mkl although it should not happen with rf-score-vs binary. Did the issue fixed itself?

**Comment by drc007** [comment]
Yes, must have been some problem with Linux install
